;function ParametreZeybuxVR() {
	this.valid = true;
	this.log = new VRelement();
	this.mailSupport = new VRelement();
	this.mailMailingListe = new VRelement();
	this.mailMailingListeDomaine = new VRelement();
	this.adresseWSDL = new VRelement();
	this.sOAPLogin = new VRelement();
	this.sOAPPass = new VRelement();
	this.zeybuxTitre = new VRelement();
	this.zeybuxAdresse = new VRelement();
	this.propNom = new VRelement();
	this.propAdresse = new VRelement();
	this.propCP = new VRelement();
	this.propVille = new VRelement();
	this.propTel = new VRelement();
	this.propMail = new VRelement();
	this.propRespMarcheNom = new VRelement();
	this.propRespMarchePrenom = new VRelement();
	this.propRespMarchePoste = new VRelement();
	this.propRespMarcheTel = new VRelement();
};