ALTER TABLE `dope_detail_operation` ADD `dope_id_modele_lot` INT NOT NULL AFTER `dope_id_detail_commande`;
ALTER TABLE `sto_stock` ADD `sto_id_modele_lot` INT NOT NULL AFTER `sto_id_detail_commande`;
ALTER TABLE `hsto_historique_stock` ADD `hsto_id_modele_lot` INT NOT NULL AFTER `hsto_id_detail_commande`;
ALTER TABLE `hdope_historique_detail_operation` ADD `hope_id_modele_lot` INT NOT NULL AFTER `hdope_id_detail_commande`;

CREATE OR REPLACE VIEW `view_achat_detail` AS select `sto_stock`.`sto_id_operation` AS `sto_id_operation`,`sto_stock`.`sto_id` AS `sto_id`,`dope_detail_operation`.`dope_id` AS `dope_id`,`sto_stock`.`sto_id_detail_commande` AS `sto_id_detail_commande`,dope_id_modele_lot,
`dope_detail_operation`.`dope_montant` AS `dope_montant`,`sto_stock`.`sto_quantite` AS `sto_quantite`,`dcom_detail_commande`.`dcom_id_produit` AS `dcom_id_produit`,`dope_detail_operation`.`dope_id_nom_produit` AS `dope_id_nom_produit` from ((`sto_stock` join `dcom_detail_commande` on((`sto_stock`.`sto_id_detail_commande` = `dcom_detail_commande`.`dcom_id`))) left join `dope_detail_operation` on(((`sto_stock`.`sto_id_operation` = `dope_detail_operation`.`dope_id_operation`) and (`sto_stock`.`sto_id_detail_commande` = `dope_detail_operation`.`dope_id_detail_commande`)))) where ((`sto_stock`.`sto_type` = 1) and (`dope_detail_operation`.`dope_type_paiement` = 7)) order by `sto_stock`.`sto_date` desc,`sto_stock`.`sto_type`;

CREATE OR REPLACE VIEW `view_achat_detail_solidaire` AS select `sto_stock`.`sto_id_operation` AS `sto_id_operation`,`sto_stock`.`sto_id` AS `sto_id`,`dope_detail_operation`.`dope_id` AS `dope_id`,`sto_stock`.`sto_id_detail_commande` AS `sto_id_detail_commande`, dope_id_modele_lot,
`dope_detail_operation`.`dope_montant` AS `dope_montant`,`sto_stock`.`sto_quantite` AS `sto_quantite`,`dcom_detail_commande`.`dcom_id_produit` AS `dcom_id_produit`,`dope_detail_operation`.`dope_id_nom_produit` AS `dope_id_nom_produit` from ((`sto_stock` join `dcom_detail_commande` on((`sto_stock`.`sto_id_detail_commande` = `dcom_detail_commande`.`dcom_id`))) left join `dope_detail_operation` on(((`sto_stock`.`sto_id_operation` = `dope_detail_operation`.`dope_id_operation`) and (`sto_stock`.`sto_id_detail_commande` = `dope_detail_operation`.`dope_id_detail_commande`)))) where ((`sto_stock`.`sto_type` = 2) and (`dope_detail_operation`.`dope_type_paiement` = 8)) order by `sto_stock`.`sto_date` desc,`sto_stock`.`sto_type`;